name       : libblocksruntime
version    : 0.4.1
release    : 1
source     :
    - http://http.debian.net/debian/pool/main/libb/libblocksruntime/libblocksruntime_0.4.1.orig.tar.gz : 7807e18d7d6cabd90f77c8b8a8ebd472516fa4ed6a02df82e0c33b1c5e112abc
license    : MIT
summary    : Blocks runtime library for Clang
description: |
    Blocks runtime library for Clang
component  : programming.library
clang      : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
